use std::{fs, path::PathBuf};

use feltnerai_api_types::*;
use ts_rs::TS;
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(components(schemas(
    ApiError,
    Branding,
    Capabilities,
    ChangePasswordRequest,
    Chat,
    ConfigureModelRequest,
    ConnectionTestResponse,
    CreateChatRequest,
    CreateProviderRequest,
    CreateUserRequest,
    GenerateRequest,
    HealthResponse,
    ImportDataResponse,
    LmStudioLoadRequest,
    LmStudioModel,
    LmStudioServerAction,
    LmStudioServerRequest,
    LmStudioStatus,
    LmStudioUnloadRequest,
    LoginRequest,
    Message,
    MessageRole,
    MessageStatus,
    Model,
    Provider,
    ProviderDraft,
    Role,
    ServerHandshake,
    ServerSettings,
    SessionResponse,
    SetupRequest,
    SetupStatus,
    StreamEvent,
    Theme,
    UpdateBrandingRequest,
    UpdateChatRequest,
    UpdateModelRequest,
    UpdateProviderRequest,
    UpdatePreferencesRequest,
    UpdateServerSettingsRequest,
    UpdateUserRequest,
    User
)))]
struct ApiDocument;

fn export<T: TS>() -> String {
    format!("export {}", T::decl())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../frontend/src/api");
    fs::create_dir_all(&root)?;

    let declarations = [
        export::<Role>(),
        export::<Theme>(),
        export::<MessageRole>(),
        export::<MessageStatus>(),
        export::<Capabilities>(),
        export::<Branding>(),
        export::<ServerHandshake>(),
        export::<HealthResponse>(),
        export::<SetupStatus>(),
        export::<ProviderDraft>(),
        export::<SetupRequest>(),
        export::<LoginRequest>(),
        export::<User>(),
        export::<SessionResponse>(),
        export::<ChangePasswordRequest>(),
        export::<UpdatePreferencesRequest>(),
        export::<CreateUserRequest>(),
        export::<UpdateUserRequest>(),
        export::<Provider>(),
        export::<CreateProviderRequest>(),
        export::<UpdateProviderRequest>(),
        export::<ConnectionTestResponse>(),
        export::<Model>(),
        export::<ConfigureModelRequest>(),
        export::<UpdateModelRequest>(),
        export::<Chat>(),
        export::<CreateChatRequest>(),
        export::<UpdateChatRequest>(),
        export::<Message>(),
        export::<GenerateRequest>(),
        export::<StreamEvent>(),
        export::<ServerSettings>(),
        export::<UpdateServerSettingsRequest>(),
        export::<UpdateBrandingRequest>(),
        export::<ImportDataResponse>(),
        export::<ApiError>(),
        export::<LmStudioModel>(),
        export::<LmStudioStatus>(),
        export::<LmStudioServerAction>(),
        export::<LmStudioServerRequest>(),
        export::<LmStudioLoadRequest>(),
        export::<LmStudioUnloadRequest>(),
    ]
    .join("\n\n");
    let source = format!(
        "// This file is generated by `just generate-api`. Do not edit.\n\n\
         export const API_MAJOR = {API_MAJOR} as const;\n\n{declarations}\n"
    );
    fs::write(root.join("generated.ts"), source)?;
    fs::write(
        root.join("openapi.json"),
        serde_json::to_vec_pretty(&ApiDocument::openapi())?,
    )?;
    println!("generated frontend/src/api/generated.ts and openapi.json");
    Ok(())
}
