// This file is generated by `just generate-api`. Do not edit.

export const API_MAJOR = 1 as const;

export type Role = "admin" | "user";

export type Theme = "light" | "dark" | "system";

export type MessageRole = "user" | "assistant";

export type MessageStatus = "complete" | "streaming" | "canceled" | "error";

export type Capabilities = {
  chat_streaming: boolean;
  portal_sessions: boolean;
  custom_branding: boolean;
};

export type Branding = {
  server_name: string;
  accent_color: string;
  logo_url: string | null;
  favicon_url: string | null;
  custom_css_url: string | null;
};

export type ServerHandshake = {
  server_uuid: string;
  api_major: number;
  version: string;
  setup_complete: boolean;
  public_url: string | null;
  capabilities: Capabilities;
  branding: Branding;
};

export type HealthResponse = { status: string; version: string };

export type SetupStatus = { complete: boolean };

export type ProviderDraft = {
  name: string;
  base_url: string;
  api_key: string | null;
  additional_headers: { [key in string]?: string } | null;
};

export type SetupRequest = {
  server_name: string;
  public_url: string | null;
  accent_color: string | null;
  username: string;
  email: string | null;
  password: string;
  provider: ProviderDraft | null;
};

export type LoginRequest = { login: string; password: string; portal: boolean };

export type User = {
  id: string;
  username: string;
  email: string | null;
  role: Role;
  disabled: boolean;
  must_change_password: boolean;
  theme: Theme;
  created_at: string;
};

export type SessionResponse = {
  user: User;
  csrf_token: string | null;
  bearer_token: string | null;
  expires_at: string;
};

export type ChangePasswordRequest = {
  current_password: string;
  new_password: string;
};

export type UpdatePreferencesRequest = { theme: Theme };

export type CreateUserRequest = {
  username: string;
  email: string | null;
  password: string;
  role: Role;
};

export type UpdateUserRequest = {
  username: string | null;
  email: string | null;
  role: Role | null;
  disabled: boolean | null;
  replacement_password: string | null;
};

export type Provider = {
  id: string;
  name: string;
  base_url: string;
  has_api_key: boolean;
  additional_header_names: Array<string>;
  enabled: boolean;
  created_at: string;
};

export type CreateProviderRequest = {
  name: string;
  base_url: string;
  api_key: string | null;
  additional_headers: { [key in string]?: string };
  enabled: boolean;
};

export type UpdateProviderRequest = {
  name: string | null;
  base_url: string | null;
  api_key: string | null;
  clear_api_key: boolean | null;
  additional_headers: { [key in string]?: string } | null;
  enabled: boolean | null;
};

export type ConnectionTestResponse = {
  ok: boolean;
  message: string;
  models: Array<string>;
};

export type Model = {
  id: string;
  provider_id: string;
  provider_name: string;
  upstream_id: string;
  display_name: string;
  enabled: boolean;
  is_default: boolean;
};

export type ConfigureModelRequest = {
  upstream_id: string;
  display_name: string;
  enabled: boolean;
  is_default: boolean;
};

export type UpdateModelRequest = {
  upstream_id: string | null;
  display_name: string | null;
  enabled: boolean | null;
  is_default: boolean | null;
};

export type Chat = {
  id: string;
  title: string;
  model_id: string | null;
  created_at: string;
  updated_at: string;
};

export type CreateChatRequest = {
  title: string | null;
  model_id: string | null;
};

export type UpdateChatRequest = {
  title: string | null;
  model_id: string | null;
};

export type Message = {
  id: string;
  chat_id: string;
  role: MessageRole;
  content: string;
  status: MessageStatus;
  model_id: string | null;
  provider_name: string | null;
  model_name: string | null;
  created_at: string;
};

export type GenerateRequest = {
  request_id: string;
  content: string;
  model_id: string | null;
};

export type StreamEvent =
  | { event: "started"; message_id: string }
  | { event: "delta"; content: string }
  | { event: "completed"; message_id: string }
  | { event: "error"; message: string };

export type ServerSettings = {
  public_url: string | null;
  trusted_proxies: Array<string>;
  data_dir: string;
  startup_supported: boolean;
  start_at_login: boolean;
  /**
   * Optional override for the LM Studio CLI (`lms`) executable path. When
   * unset the server auto-detects `lms` on PATH and in default install
   * locations.
   */
  lmstudio_cli_path: string | null;
};

export type UpdateServerSettingsRequest = {
  public_url: string | null;
  trusted_proxies: Array<string> | null;
  start_at_login: boolean | null;
  /**
   * Set to `Some("")` to clear the override and fall back to auto-detection.
   */
  lmstudio_cli_path: string | null;
};

export type UpdateBrandingRequest = {
  server_name: string | null;
  accent_color: string | null;
  custom_css: string | null;
};

export type ImportDataResponse = { restart_required: boolean; message: string };

export type ApiError = { code: string; message: string };

export type LmStudioModel = {
  /**
   * Identifier passed to `lms load`/`lms unload` (the model key/path).
   */
  id: string;
  /**
   * Friendly display name when LM Studio reports one.
   */
  display_name: string | null;
  /**
   * Size on disk in bytes when known.
   */
  size_bytes: number | null;
};

export type LmStudioStatus = {
  /**
   * Whether the `lms` executable could be located and invoked.
   */
  cli_available: boolean;
  /**
   * Resolved path to the `lms` executable, when found.
   */
  cli_path: string | null;
  /**
   * `lms version` output, when available.
   */
  version: string | null;
  /**
   * Whether the LM Studio local OpenAI-compatible server is running.
   */
  server_running: boolean;
  /**
   * Base URL of the LM Studio local server when running.
   */
  server_url: string | null;
  /**
   * Models downloaded and available to load.
   */
  downloaded: Array<LmStudioModel>;
  /**
   * Models currently loaded into memory.
   */
  loaded: Array<LmStudioModel>;
  /**
   * Human-readable note (e.g. install hint) surfaced to admins.
   */
  message: string | null;
};

export type LmStudioServerAction = "start" | "stop";

export type LmStudioServerRequest = { action: LmStudioServerAction };

export type LmStudioLoadRequest = {
  model: string;
  context_length: number | null;
};

export type LmStudioUnloadRequest = {
  /**
   * Specific model to unload, or `None` to unload everything.
   */
  model: string | null;
};
